config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
  end

  root 'toppages#index'

  resources :mypages do
    collection do
      get 'logout'
      get 'payment'
    end
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase do
    member do
      post 'pay', to: 'purchase#pay'
      get 'index', to: 'purchase#index'
      get 'done', to: 'purchase#done'      
    end
  end

  # resources :login, only: [:index, :new]
  resources :toppages, only: :index
  resources :login, only: :new
  
  resources :items do 
    #Ajaxで動くアクションのルートを作成
    collection do
      get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
      get 'delete',to: 'items#delete'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  validates :customer_id, presence: true
  validates :card_id, presence: true

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
end

app/models/condition.rb
class Condition < ActiveHash::Base

    self.data = [
    {id: 1, name: '新品、未使用'}, 
    {id: 2, name: '未使用に近い'},
    {id: 3, name: '目立った傷や汚れなし'}, 
    {id: 4, name: 'やや傷や汚れあり'},
    {id: 5, name: '傷や汚れあり'}, 
    {id: 6, name: '全体的に状態が悪い'}
    ]

  include ActiveHash::Associations
  has_many :items

end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :user, optional: true
  validates :ship_last_name, :ship_first_name, :ship_last_name_kana, :ship_first_name_kana, :phone_number, :zip_code, :prefecture, :address, :second_address ,presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  
  mount_uploader :image, ImageUploader

  validates :image, presence: true

  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord

  validates :images, presence: true
  validates_associated :images
  validates :item_name, presence: true,length:{maximum:40}
  validates :description, presence: true,length:{maximum:1000}
  validates :category_id, presence: true
  validates :condition, presence: true
  validates :preparation, presence: true
  validates :postage, presence: true
  validates :prefecture, presence: true
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}

  has_many :images, dependent: :destroy
  belongs_to :category
  belongs_to :user
  accepts_nested_attributes_for :images, allow_destroy: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :condition
  belongs_to_active_hash :preparation
  belongs_to_active_hash :postage

end

app/models/postage.rb
class Postage < ActiveHash::Base
  
  self.data = [
    {id: 1, name: '送料込み（出品者負担）'}, 
    {id: 2, name: '着払い（購入者負担）'}
  ]
  
  include ActiveHash::Associations
  has_many :items
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base

  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
  
  include ActiveHash::Associations
  has_many :items
end

app/models/preparation.rb
class Preparation < ActiveHash::Base
  
  self.data = [
    {id: 1, days: '1~2日で発送'}, 
    {id: 2, days: '2~3日で発送'}, 
    {id: 3, days: '4~7日で発送'}
  ]
  
  include ActiveHash::Associations
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, password_length: 7..128
  validates :nickname, :last_name, :first_name, :last_name_kana, :first_name_kana, :birthday, presence: true
  has_one :destination, dependent: :destroy
  has_one :credit_card, dependent: :destroy
  has_many :items
end

app/controllers/card_controller.rb
class CardController < ApplicationController

  require "payjp"

  def new
    if user_signed_in?
      card = Card.where(user_id: current_user.id)
      redirect_to action: "show" if card.exists?
    else
      redirect_to new_login_path
      flash[:notice] = '購入するにはログイン・新規登録してください'
    end
  end

  def pay
    Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) 
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  def show
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @items = Item.includes(:images).order('updated_at DESC').first(4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/toppages/_app_banner.html.haml
%aside.appBanner
  .inner
    %h2.inner__title 誰でもかんたん、人生を変えるフリマアプリ
    %p.inner__text 今すぐ無料ダウンロード！
    .inner__icon
      = link_to '#' do
        = image_tag 'app-store.svg', class: "linkIcon aBtn"
      = link_to '#' do
        = image_tag 'google-play.svg', class: "linkIcon gBtn" 

app/views/toppages/_footer.html.haml
.footer
  %ul.footer__contents
    %li.content
      %h2.content__head FURIMAについて
      %ul
        %li
          = link_to '#' do
            会社概要(運営会社)
        %li
          = link_to '#' do
            プライバシーポリシー
        %li
          = link_to '#' do
            FURIMA利用規約
        %li
          = link_to '#' do
            ポイントに関する特約
    %li.content
      %h2.content__head FURIMAを見る
      %ul
        %li
          = link_to '#' do
            カテゴリー一覧
        %li
          = link_to '#' do
            ブランド一覧
    %li.content
      %h2.content__head ヘルプ&ガイド
      %ul
        %li
          = link_to '#' do
            FURIMAガイド
        %li
          = link_to '#' do
            FURIMAロゴ利用ガイドライン
        %li
          = link_to '#' do
            お知らせ
  .footer__logo
    = link_to root_path do
      = image_tag 'logo-white.svg', alt: 'logo'
  %p ©️ FURIMA 

app/views/toppages/_header.html.haml
%header.pcHeader
  .headerInner
    .mainHeader
      %h1.icon
        = link_to root_path do
          = image_tag 'logo-.svg', alt: 'icon'
      .searchBox
        = form_with url: '#', method: :get, local: true do |f|
          = f.text_field :searchInput, name: "key", class: "searchBox--input", placeholder: "キーワードから探す"
          %button{type: "submit"}
            .searchBox__icon
              = image_tag 'icon-search.svg', alt: 'icon'
      %ul.resultLists
    .nav
      %ul.listsLeft
        %li.listsLeft__item.listsLeft__item--first
          = link_to '#', id: "catBtn" do
            カテゴリー
          .tree.displayNone
            %ul.categoryTree
              %li.categoryTree--item
                = link_to '#', id: "1" do
                  レディース
              %li.categoryTree--item
                = link_to '#', id: "2" do
                  メンズ                
              %li.categoryTree--item
                = link_to '#', id: "3" do
                  ベビー・キッズ
              %li.categoryTree--item
                = link_to '#', id: "4" do
                  インテリア・住まい・小物
              %li.categoryTree--item
                = link_to '#', id: "5" do
                  本・音楽・ゲーム
              %li.categoryTree--item
                = link_to '#', id: "6" do
                  おもちゃ・ホビー・グッズ
              %li.categoryTree--item
                = link_to '#', id: "7" do
                  コスメ・香水・美容
              %li.categoryTree--item
                = link_to '#', id: "8" do
                  家電・スマホ・カメラ                  
              %li.categoryTree--item
                = link_to '#', id: "9" do
                  スポーツ・レジャー
              %li.categoryTree--item
                = link_to '#', id: "10" do
                  ハンドメイド
              %li.categoryTree--item
                = link_to '#', id: "11" do
                  チケット
              %li.categoryTree--item
                = link_to '#', id: "12" do
                  自動車・オートバイ
              %li.categoryTree--item
                = link_to '#', id: "13" do
                  その他
        %li.listsLeft__item
          = link_to '#', id: "brandBtn" do
            ブランド
          %ul.brandsPulldown.displayNone
      %ul.listsRight
      - if user_signed_in?
        .listsRight__item__hello
          こんにちは
          %span #{current_user.nickname}
          さん
        %li.listsRight__item.listsRight__item--login
          = link_to destroy_user_session_path, method: :delete do
            ログアウト
        %li.listsRight__item.listsRight__item--new    
          = link_to 'マイページ', mypage_path(current_user.id)
      - else
        .listsRight__item__hello
          こんにちは
          %span ゲスト
          さん
        %li.listsRight__item.listsRight__item--login
          = link_to new_user_session_path do
            ログイン
        %li.listsRight__item.listsRight__item--new
          = link_to new_login_path do
            新規会員登録

app/views/toppages/index.html.haml
= render "header"

.main
  %section.mainVisual
    .content
      %h2.content__subtitle
        %br/
        人生を変えるフリマアプリ
      %p.content__text
        FURIMAは誰でも簡単に出品・購入できる 
        %br/
        フリマアプリです
      .content__btn
        = link_to "#", class: "aBtn" do
          = image_tag 'app-store.svg', alt: 'apple'
        = link_to "#", class: "gBtn" do
          = image_tag 'google-play.svg', alt: 'google'
  %section.topIntroduction
    %h2.subtitle
      FURIMAが選ばれる3つの理由
    %ul.lists
      %li.list
        .list__pict
          %span.number 1
          = image_tag 'pict-reason-01-77b.jpg', alt: 'reason'
        %h3.list__text
          %span 3分
          ですぐに出品
        %p.list__description
          スマホで入力するでけで簡単に出品できる！
      %li.list
        .list__pict
          %span.number 2
          = image_tag 'pict-reason-02.jpg', alt: 'reason02'
        %h3.list__text
          %span シンプル
          で使いやすい
        %p.list__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.list.list--last
        .list__pict
          %span.number 3
          = image_tag 'pict-reason-03.jpg', alt: 'reason3'
        %h3.list__text 
          手数料
          %span 業界最安
        %p.list__description
          最大3%でお得に出品&購入！
  %section.topMiddleDL
    .topMiddleDL__inner
      %h2.subtitle 
        会員数日本一位
      %p.text
        FURIMAは、フリマアプリで最も人気
        %br/
        出品・購入回数も業界最多です！
        %br/
        ほしかったあの商品に出会えるかもしれません
      .btn
        = link_to "#" do
          = image_tag 'app-store.svg', alt: 'apple', class: "aBtn"
        = link_to "#" do
          = image_tag 'google-play.svg', alt: 'google', class: "gBtn"
  %section.topKeyFeatures
    %h2.head
      FURIMAの特徴
    .items
      %section.item
        %figure.item__img
          = image_tag 'icon-01-7.svg', alt: 'man'
        %h3.item__subtitle
          簡単に売り買いできる
        %p.item__detail
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %section.item
        %figure.item__img
          = image_tag 'icon-03.svg', alt: 'woman'
        %h3.item__subtitle
          売上金は即日振込に対応
        %p.item__detail
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします！
      %section.item
        %figure.item__img
          = image_tag 'icon-04.svg', alt: 'wallet'
        %h3.item__subtitle
          様々な支払いに対応
        %p.item__detail
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  %section.pickupContainer
    %h2.head ピックアップカテゴリー
    .productBox
      .productHead
        = link_to items_path do
          %h3.title 新規投稿商品
      .productLists
        - @items.each do |item|
          .productList
            = link_to item_path(item.id) do
              %figure.productList--img
                = image_tag item.images.first.image.url
                  - if item.buyer_id.present?
                  .items-box_photo__sold
                    .items-box_photo__sold__inner 
                      SOLD
              .productList--body
                %h3.name
                  = item.item_name
                .details
                  %ul
                    %li
                      = (item.price / 0.9).floor.to_s(:delimited)
                      円
                    %li
                      %i.fa.fa-star.likeIcon 0
                  %p (税込)
  %section.pickupContainer
    %h2.head ピックアップブランド
    .productBox
      .productHead
        = link_to items_path do
          %h3.title アーカイブ
      .productLists
        - @items.each do |item|
          .productList
            = link_to item_path(item.id) do
              %figure.productList--img
                = image_tag item.images.first.image.url
                  - if item.buyer_id.present?
                  .items-box_photo__sold
                    .items-box_photo__sold__inner 
                      SOLD
              .productList--body
                %h3.name
                  = item.item_name
                .details
                  %ul
                    %li
                      = (item.price / 0.9).floor.to_s(:delimited)
                      円
                    %li
                      %i.fa.fa-star.likeIcon 0
                  %p (税込)

= render "app_banner"
= render "footer"
= render "purchaseBtn"