config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
  end

  root 'toppages#index'

  resources :mypages do
    collection do
      get 'logout'
      get 'payment'
    end
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase do
    member do
      post 'pay', to: 'purchase#pay'
      get 'index', to: 'purchase#index'
      get 'done', to: 'purchase#done'      
    end
  end

  # resources :login, only: [:index, :new]
  resources :toppages, only: :index
  resources :login, only: :new
  
  resources :items do 
    #Ajaxで動くアクションのルートを作成
    collection do
      get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
      get 'delete',to: 'items#delete'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  validates :customer_id, presence: true
  validates :card_id, presence: true

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
end

app/models/condition.rb
class Condition < ActiveHash::Base

    self.data = [
    {id: 1, name: '新品、未使用'}, 
    {id: 2, name: '未使用に近い'},
    {id: 3, name: '目立った傷や汚れなし'}, 
    {id: 4, name: 'やや傷や汚れあり'},
    {id: 5, name: '傷や汚れあり'}, 
    {id: 6, name: '全体的に状態が悪い'}
    ]

  include ActiveHash::Associations
  has_many :items

end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :user, optional: true
  validates :ship_last_name, :ship_first_name, :ship_last_name_kana, :ship_first_name_kana, :phone_number, :zip_code, :prefecture, :address, :second_address ,presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  
  mount_uploader :image, ImageUploader

  validates :image, presence: true

  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord

  validates :images, presence: true
  validates_associated :images
  validates :item_name, presence: true,length:{maximum:40}
  validates :description, presence: true,length:{maximum:1000}
  validates :category_id, presence: true
  validates :condition, presence: true
  validates :preparation, presence: true
  validates :postage, presence: true
  validates :prefecture, presence: true
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}

  has_many :images, dependent: :destroy
  belongs_to :category
  belongs_to :user
  accepts_nested_attributes_for :images, allow_destroy: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :condition
  belongs_to_active_hash :preparation
  belongs_to_active_hash :postage

end

app/models/postage.rb
class Postage < ActiveHash::Base
  
  self.data = [
    {id: 1, name: '送料込み（出品者負担）'}, 
    {id: 2, name: '着払い（購入者負担）'}
  ]
  
  include ActiveHash::Associations
  has_many :items
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base

  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
  
  include ActiveHash::Associations
  has_many :items
end

app/models/preparation.rb
class Preparation < ActiveHash::Base
  
  self.data = [
    {id: 1, days: '1~2日で発送'}, 
    {id: 2, days: '2~3日で発送'}, 
    {id: 3, days: '4~7日で発送'}
  ]
  
  include ActiveHash::Associations
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, password_length: 7..128
  validates :nickname, :last_name, :first_name, :last_name_kana, :first_name_kana, :birthday, presence: true
  has_one :destination, dependent: :destroy
  has_one :credit_card, dependent: :destroy
  has_many :items
end

app/controllers/card_controller.rb
class CardController < ApplicationController

  require "payjp"

  def new
    if user_signed_in?
      card = Card.where(user_id: current_user.id)
      redirect_to action: "show" if card.exists?
    else
      redirect_to new_login_path
      flash[:notice] = '購入するにはログイン・新規登録してください'
    end
  end

  def pay
    Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) 
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  def show
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  def index

  end

  def show
    @destination = Destination.find(params[:id])
    @user = User.find(params[:id])
  end

  def logout

  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/mypages/_side_bar.html.haml
//マイページのコンテンツの左側のメニューバー
.sidelist
  %table
    %tr
      %td.list.mypage
        = link_to "　トップページ", root_path, class:"tabel-btn"
    %tr
      %td.list.mypage
        = link_to "　マイページ/ユーザー登録情報", mypage_path(current_user.id), class:"tabel-btn"
    %tr
      %td.list.listed-products
        = link_to "　出品した商品", "#", class:"tabel-btn"
        
    %tr
      %td.list.purchased-product
        = link_to "　購入した商品", "#", class:"tabel-btn"
    
    %tr  
      %td.list.purchased-product
        = link_to "　出品する", "#", class:"tabel-btn"

    %tr
      %td.list.payment
        = link_to "　支払い方法", new_card_path, class:"tabel-btn","data-turbolinks": false

    %tr
      %td.list.logout
        = link_to "　ログアウト", logout_mypages_path, class:"tabel-btn"

app/views/mypages/destroy.html.haml
= render "toppages/header"

.done#fullsize
  .done__title
    商品を削除しました
  .done__backlink
    = link_to 'トップページへ戻る', root_path, class: 'link'

= render "toppages/footer"
= render "toppages/purchaseBtn"

app/views/mypages/logout.html.haml
= render "toppages/header"
.logout-wrapper
  = render 'mypages/side_bar'
  .contents
    .contents__logout
      = link_to "ログアウトする", destroy_user_session_path, method: :delete, class: 'logout-btn'
= render "toppages/footer"

app/views/mypages/payment.html.haml
.payment-wrapper
  = render 'mypages/side_bar'

  .contents
    .contents-head
      %h2 クレジットカード情報入力

    .contents__credit-card
      .contents__credit-card__number
        = form_with url: "#", method: :post, html: { name: "inputForm" } do |f|
          = f.label :カード番号, class: 'label'
          %span 必須
          %br
          = f.text_field :card_number, type: 'text', class: 'input-number', placeholder: '半角数字のみ', maxlength: "16"

          %ul.card-list
            %li 
              = image_tag "/material/icon/visa.svg", size: "49x20"
            %li
              = image_tag "/material/icon/master-card.svg", size: "34x20"
            %li
              = image_tag "/material/icon/saison-card.svg", size: "30x20"
            %li
              = image_tag "/material/icon/jcb.svg", size: "32x20"
            %li
              = image_tag "/material/icon/american_express.svg", size: "21x20"
            %li
              = image_tag "/material/icon/dinersclub.svg", size: "32x20"
            %li
              = image_tag "/material/icon/discover.svg", size: "32x20"
 
          .contents__credit-card__expiration
            = f.label :有効期限, class: 'label'
            %span 必須
            %br
            .contents__credit-card__expiration__wrap
              = f.select :exp_month,[["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'input-expiration'
              %span.expiration 月
              = f.select :exp_year,[["19",2019],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , class: 'input-expiration'
              %span.expiration 年

          .contents__credit-card__security-code
            = f.label :セキュリティコード, class: 'label'
            %span 必須
            %br
            = f.text_field :cvc, type: 'text', class: 'input-number', placeholder: 'カード背面4桁もしくは3桁の番号', maxlength: "4"
          .content-bottom
            = f.submit '追加する', class: 'add-btn' 

app/views/mypages/show.html.haml
= render "toppages/header"
.mypage-wrapper
  = render 'mypages/side_bar'

  .contents
    .mypage-info-wrapper
      .mypage-contents__userinfo-head
        %h2 ユーザー登録情報
      .mypage-contents__userinfo-wrapper
        .mypage-contents__userinfo-wrapper__name
          %h1.info お名前
          = @destination.ship_last_name
          = @destination.ship_first_name
          %br
        .mypage-contents__userinfo-wrapper__kananame
          %h1.info お名前カナ
          = @destination.ship_last_name_kana
          = @destination.ship_first_name_kana
        .mypage-contents__userinfo-wrapper__birthday
          %h1.info 生年月日
          //gsub!メソッドは文字列の中の指定の文字を変換する。
          //第一引数を第二引数に変換する。
          = @user.birthday.to_s.gsub!("-","/")
        .mypage-contents__userinfo-wrapper__zipcode
          %h1.info 郵便番号
          = "〒" + @destination.zip_code.to_s.insert(3, '-')
        .mypage-contents__userinfo-wrapper__address
          %h1.info 配送先住所
          = @destination.prefecture + @destination.address + @destination.second_address
          = @destination.building_name
        .mypage-contents__userinfo-wrapper__phone_number
          %h1.info 連絡先(携帯電話)
          = "0" + @destination.phone_number.to_s[0..1] + "-" + @destination.phone_number.to_s[2..5] + "-" + @destination.phone_number.to_s[6..9]
        .mypage-contents__userinfo-wrapper__email
          %h1.info メールアドレス
          = @user.email

= render "toppages/footer"
= render "toppages/purchaseBtn"