config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
  end

  root 'toppages#index'

  resources :mypages do
    collection do
      get 'logout'
      get 'payment'
    end
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase do
    member do
      post 'pay', to: 'purchase#pay'
      get 'index', to: 'purchase#index'
      get 'done', to: 'purchase#done'      
    end
  end

  # resources :login, only: [:index, :new]
  resources :toppages, only: :index
  resources :login, only: :new
  
  resources :items do 
    #Ajaxで動くアクションのルートを作成
    collection do
      get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
      get 'delete',to: 'items#delete'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord

  validates :images, presence: true
  validates_associated :images
  validates :item_name, presence: true,length:{maximum:40}
  validates :description, presence: true,length:{maximum:1000}
  validates :category_id, presence: true
  validates :condition, presence: true
  validates :preparation, presence: true
  validates :postage, presence: true
  validates :prefecture, presence: true
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}

  has_many :images, dependent: :destroy
  belongs_to :category
  belongs_to :user
  accepts_nested_attributes_for :images, allow_destroy: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :condition
  belongs_to_active_hash :preparation
  belongs_to_active_hash :postage

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :category_parent_array, only: [ :edit, :update]
  before_action :set_item, except: [:index, :new, :create, :delete, :get_category_children, :get_category_grandchildren]
  before_action :show_all_instance, only: [ :edit, :show, :destroy, :update]
  before_action :authenticate_user!, only: [:new, :destroy, :edit]

  def index
    @items = Item.includes(:images).order('created_at DESC')
  end

  def new
    @item = Item.new
    @item.images.new
    @category_parent_array = ["---"]
    @category_parent_array = Category.where(ancestry: nil)
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
      flash[:notice] = '出品が完了しました！'
    else
      flash[:alert] = '必須項目を入力してください'
      render :new
    end
  end

  def show
    @items = Item.includes(:images)
    @user = User.find_by(id: @item.user_id)
    @category = Category.find(params[:id])
    @categories = Category.find(params[:id])
  end

  def edit
    grandchild = @item.category
    child = grandchild.parent

    if  @category_parent.nil? || @category_child.nil? || @category_grandchild.nil?
      flash[:alert] = 'この商品は必須項目が不十分のため編集できません。削除し出品をやり直してください。'
      redirect_to item_path
      
    else

      @parent_array = []
      @parent_array << @item.category.parent.parent.name
      @parent_array << @item.category.parent.parent.id
    
    end
      @category_children_array = Category.where(ancestry: child&.ancestry)
      @child_array = []
      @child_array << child.name
      @child_array << child.id
      
      @category_grandchildren_array = Category.where(ancestry: grandchild.ancestry)
      @grandchild_array = []
      @grandchild_array << grandchild.name
      @grandchild_array << grandchild.id
  end

  def update
    if item_params[:images_attributes].nil? 
      flash[:alert] = '画像は１枚以上入れてください。'
      redirect_to edit_item_path  
    elsif item_params[:category_id] == "---"
      flash[:alert] = 'カテゴリーは全て選択してください'
      redirect_to edit_item_path 
    elsif
      exit_ids = []
      item_params[:images_attributes].each do |a,b|
        exit_ids << item_params[:images_attributes].dig(:"#{a}",:id).to_i
      end
      ids = Image.where(item_id: params[:id]).map{|image| image.id }
      delete__db = ids - exit_ids
      Image.where(id:delete__db).destroy_all
      @item.touch
      if @item.update(item_params)
         redirect_to root_path
      else
        flash[:alert] = '更新できませんでした'
        render :edit
      end
    end
  end

  def destroy
    if @item.user.id == current_user.id && @item.destroy
       redirect_to delete_items_path
    else
      redirect_to item_path(@item.id)
      flash.now[:alert] = '商品の削除に失敗しました'
    end
  end


  def get_category_children
    @category_children = Category.find(params[:parent_id]).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  private

  def item_params
    params.require(:item).permit(:item_name, :description, :category_id, :brand, :condition_id, :postage_id, :prefecture_id, :preparation_id, :price, images_attributes: [:image, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def category_parent_array
    @category_parent_array = Category.where(ancestry: nil)
  end

  def show_all_instance
    @user = User.find(@item.user_id)
    @images = Image.where(item_id: params[:id])
    @images_first = Image.where(item_id: params[:id]).first
    @category_id = @item.category_id
    @category_parent = Category.find(@category_id).parent.parent
    @category_child = Category.find(@category_id).parent
    @category_grandchild = Category.find(@category_id)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item.html.haml
%li.images
  = image_tag item.images.first.image.url, class:"image1"
  -if @item.buyer_id.present?
    .items-box_photo__sold
      .items-box_photo__sold__inner SOLD

app/views/items/delete.html.haml
= render "toppages/header"
.delete-done
  .delete-done__title
    商品を削除しました
    -# <meta http-equiv="Refresh" content="5; url=/toppages">
    //metaタグはiOSでは動作しないため、javaScriptに変更
    %body{:onload => "setTimeout(\"location.href='/toppages'\",5000)"}
    %p 5秒後にトップページへ移動します
    = link_to 'トップページへ戻る', root_path, class: 'link'
= render "toppages/footer"
= render "toppages/purchaseBtn"

app/views/items/done.html.haml
= render "toppages/header"

.done#fullsize
  .done__title
    商品を削除しました
  .done__backlink
    = link_to 'トップページへ戻る', root_path, class: 'link'

= render "toppages/footer"
= render "toppages/purchaseBtn"

app/views/items/edit.html.haml
.ExhibitionWrapper
  .ExhibitionHeader
    = link_to image_tag('logo.svg', alt: 'ヘッダーロゴ'), root_path, class: "ExhibitionHeaderLogo"
  .ExhibitionBox
    = form_with model: @item, local: true, class: "ExhibitionForm" do |f|
      .ImageForm
        .ImageLabel
          %label 出品画像
          %span 必須
        %p.ImageInfo 最大5枚までアップロードできます
        #image-box-1{class:"#{@images.last.id}"}
          - @images.each do |img|
            .item-image{id:img.id}
              = image_tag(img.image.url)
              .item-image__operetion
                .item-image__operetion--edit__delete__hidden 削除
          %label.img-label{for: "img-file"}
            = icon('fas', 'camera', class: 'EditUploadCamera')
            .displayhide
              #image-box__container{class:"item-num-#{@images.length}"}
                #append-js-edit
                  = f.fields_for :images do |image|
                    .js-file_group{"data-index" => "#{image.index}"}
                      = image.file_field :image, type: 'file', value:"#{image.object.id}",style: "",  id:"img-file", class:'js-file-edit',name: "item[images_attributes][#{@item.images.count}][image]", data:{index:""}
      .ExplanationForm
        .FormLabel
          %label 商品名
          %span 必須
        = f.text_field :item_name, placeholder:"40文字まで", class: "InputForm"
        .FormLabel
          %label 商品の説明
          %span 必須
        = f.text_area :description, class: "InputForm-TextArea"
        .WordCountBox
          %span.WordCount 0/1000
      .DetailsForm
        %p.DetailsTitle 商品の詳細
        .FormLabel
          %label カテゴリー
          %span 必須
        .CategoryBox
          .CategoryBoxChoose
            .category
              =f.collection_select :category_id, @category_parent_array, :id, :name,{selected:@parent_array}, {class:"serect_field",id:'parent_category'}   
            .category__child#children_wrapper
              =f.collection_select :category_id, @category_children_array, :id, :name, {selected:@child_array}, {id:"child__category", class:"serect_field"}
            .category__grandchild#grandchildren_wrapper
              =f.collection_select :category_id, @category_grandchildren_array, :id, :name, {selected:@grandchild_array}, {class:"serect_field"}
        .FormLabel
          %label ブランド
          %span.other-span 任意

        .FormLabel
          %label ブランド
          %span.other-span 任意
        = f.text_field :brand, placeholder:"例） シャネル",  class: "InputForm"
        .FormLabel
          %label 商品の状態
          %span 必須
        .ConditionBox
          = f.collection_select :condition_id, Condition.all, :id, :name,{include_blank: "選択してください"}, {class: "SelectForm"}
      .ShippingForm
        .AboutShip
          %p.ShipLink 配送について
          =link_to '#', class: "HelpLink" do
            = icon('far', 'question-circle', class: 'LinkIcon')
        .FormLabel
          %label 配送量の負担
          %span 必須
        .PostagePayerBox
          = f.collection_select :postage_id, Postage.all, :id, :name,{include_blank: "選択してください"}, {class: "SelectForm"}
        .FormLabel
          %label 発送元の地域
          %span 必須
        .ShipFromBox
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name,{include_blank: "選択してください"}, {class: "SelectForm"}
        .FormLabel
          %label 発送までの日数
          %span 必須
        .ShipPreparationBox
          = f.collection_select :preparation_id, Preparation.all, :id, :days,{include_blank: "選択してください"}, {class: "SelectForm"}
      .PriceForm
        .PriceBox
          .PriceTitle
            .PriceRange 価格（¥300〜9,999,999）
            =link_to '#', class: "AboutPriceLink" do
              = icon('far', 'question-circle', class: 'LinkIcon')
          .PriceSelectBox
            .PriceLabelBox
              %label 販売価格
              %span 必須
            .Yen ¥
            .PriceFormBox
              %input#price_calc.PriceSelect{type: "number", value: (@item.price / 0.9).floor}
        .SalesCommissionBox
          .CommissionTitle
            %p 販売手数料（10%)
          .SalesCommission
        .SalesProfit
          .CommissionTitle
            %p 販売利益
          = f.number_field :price, style: "display: none", id: "price"
          .SalesCommission_2
      .ExhibitionButtons
        = f.submit '再投稿する',class:'ExhibitionBTN'   
        = f.submit '下書きに保存', class: 'SaveBTN'
        = link_to 'もどる', '#', class: 'BackLink'
      .AttentionBox
        .AttentionText
          禁止されている
          = link_to '行為', '#'
          および
          = link_to '出品物', '#'
          を必ずご確認ください。
          = link_to '偽ブランド品', '#'
          や
          = link_to '盗品物', '#'
          などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして
          = link_to '加盟店規約', '#'
          に同意したことになります。
  .ExhibitionFooter
    %ul.Info
      %li
        = link_to 'プライバシーポリシー', '#'
      %li.CenterInfo
        = link_to 'フリマ利用規約', '#'
      %li
        = link_to '特定商取引に関する表記', '#'
    = link_to image_tag('logo-white.svg', alt: 'フッターロゴ', width: 214, height: 62), "/", class: "ExhibitionFooterLogo"

app/views/items/index.html.haml
= render "toppages/header"
.item__body
  %h3.item__body__title 新規投稿商品一覧
  .item__body__lists
    - @items.each do |item|
      .item__body__lists__list
        = link_to item_path(item.id) do
          %figure.list__img
            = image_tag item.images.first.image.url
              - if item.buyer_id.present?
              .items-box_photo__sold
                .items-box_photo__sold__inner
                  SOLD
          .list__body
            %h3.name
              = item.item_name
            .list__price
              %ul
                %li

                  = (item.price / 0.9).floor

                  円
                %li
                  %i.fa.fa-star.likeIcon 0
              %p (税込)
= render "toppages/app_banner"
= render "toppages/footer"
= render "toppages/purchaseBtn" 

app/views/items/new.html.haml
.ExhibitionWrapper
  .ExhibitionHeader
    = link_to image_tag('logo.svg', alt: 'ヘッダーロゴ'), "/", class: "ExhibitionHeaderLogo"
  .ExhibitionBox
    = form_with model: @item, local: true, class: "ExhibitionForm" do |f|
      .ImageForm
        .ImageLabel
          %label 出品画像
          %span 必須
        %p.ImageInfo 最大5枚までアップロードできます
        .ImageBox
          = f.fields_for :images do |image|
            %ul#previews
              %li.input
                %label.upload-label
                  = icon('fas', 'camera', class: 'UploadCamera')
                  .input-area
                    = image.file_field :image, class: "hidden image_upload"
      .ExplanationForm
        .FormLabel
          %label 商品名
          %span 必須
        = f.text_field :item_name, placeholder:"40文字まで", class: "InputForm"
        .FormLabel
          %label 商品の説明
          %span 必須
        = f.text_area :description, class: "InputForm-TextArea"
        .WordCountBox
          %span.WordCount 0/1000
      .DetailsForm
        %p.DetailsTitle 商品の詳細
        .FormLabel
          %label カテゴリー
          %span 必須
        .CategoryBox
          .CategoryBoxChoose
            = f.collection_select :category_id, Category.where(ancestry: nil), :id, :name, {prompt: '---'}, {id: 'parent_category'}
        .FormLabel
          %label ブランド
          %span.other-span 任意
        = f.text_field :brand, placeholder:"例） シャネル",  class: "InputForm"
        .FormLabel
          %label 商品の状態
          %span 必須
        .ConditionBox
          = f.collection_select :condition_id, Condition.all, :id, :name,{include_blank: "選択してください"}, {class: "SelectForm"}
      .ShippingForm
        .AboutShip
          %p.ShipLink 配送について
          =link_to '#', class: "HelpLink" do
            = icon('far', 'question-circle', class: 'LinkIcon')
        .FormLabel
          %label 配送量の負担
          %span 必須
        .PostagePayerBox
          = f.collection_select :postage_id, Postage.all, :id, :name,{include_blank: "選択してください"}, {class: "SelectForm"}
        .FormLabel
          %label 発送元の地域
          %span 必須
        .ShipFromBox
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name,{include_blank: "選択してください"}, {class: "SelectForm"}
        .FormLabel
          %label 発送までの日数
          %span 必須
        .ShipPreparationBox
          = f.collection_select :preparation_id, Preparation.all, :id, :days,{include_blank: "選択してください"}, {class: "SelectForm"}
      .PriceForm
        .PriceBox
          .PriceTitle
            .PriceRange 価格（¥300〜9,999,999）
            =link_to '#', class: "AboutPriceLink" do
              = icon('far', 'question-circle', class: 'LinkIcon')
          .PriceSelectBox
            .PriceLabelBox
              %label 販売価格
              %span 必須
            .Yen ¥
            .PriceFormBox
              %input#price_calc.PriceSelect{placeholder: "0", type: "number"}/
        .SalesCommissionBox
          .CommissionTitle
            %p 販売手数料（10%)
          .SalesCommission
        .SalesProfit
          .CommissionTitle
            %p 販売利益
          = f.number_field :price, style: "display: none", id: "price"
          .SalesCommission_2
      .ExhibitionButtons
        = f.submit '出品する', class: 'ExhibitionBTN'   
        = f.submit '下書きに保存', class: 'SaveBTN'
        = link_to 'もどる', '#', class: 'BackLink'
      .AttentionBox
        .AttentionText
          禁止されている
          = link_to '行為', '#'
          および
          = link_to '出品物', '#'
          を必ずご確認ください。
          = link_to '偽ブランド品', '#'
          や
          = link_to '盗品物', '#'
          などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして
          = link_to '加盟店規約', '#'
          に同意したことになります。
  .ExhibitionFooter
    %ul.Info
      %li
        = link_to 'プライバシーポリシー', '#'
      %li.CenterInfo
        = link_to 'フリマ利用規約', '#'
      %li
        = link_to '特定商取引に関する表記', '#'
    = link_to image_tag('logo-white.svg', alt: 'フッターロゴ', width: 214, height: 62), "/", class: "ExhibitionFooterLogo"

app/views/items/show.html.haml
= render "toppages/header"

.main
  .showMain
    .contentLeftqq
    .contentRight
      .topContent
        .itemBox
          %h2.itemBox__name
            商品名 
            = @item.item_name
          .itemBox__body
            %ul.ul1
              = render partial: 'item' ,locals: {item: @item}
            %ul.ul2
              - @item.images.each do |image|
                %li.li1
                  = image_tag image.image.url, class: "image2"
          .itemBox__price
            %span1
              = (@item.price / 0.9).floor.to_s(:delimited)
              円
            .priceDetail
              %span
                (税込み)
              %span
                送料込み
          .itemDetail
            = @item.description
          .table
            %table
              %tr
                %th 出品者
                %td 
                  = @user.nickname
              %tr
                %th カテゴリー
                %td 
                  = link_to "#" do
                    = @item.category&.parent&.parent&.name
                    %br/
                  = link_to "#" do
                    = @item.category&.parent&.name
                    %br/
                  = link_to "#" do
                    = @item.category&.name
                    %br/
              %tr
                %th ブランド
                %td
                  = @item.brand
              %tr
                %th 商品のサイズ
                %td 
              %tr
                %th 商品の状態
                %td 
                  = @item.condition.name
              %tr
                %th 配送料の負担
                %td 
                  = @item.postage.name
              %tr
                %th 発送元の地域
                %td 
                  = link_to "#" do
                    = @item.prefecture.name    
                  %br/
              %tr
                %th 発送元の目安
                %td 
                  = @item.preparation.days
          .optionalArea 
            %ul
              %li.likeBtn#likeBtn
                %i.fa.fa-star 
                  お気に入り 0
            %ul.optional
              %li.optionalBtn 
                = link_to "#" do
                  %i.fa.fa-flag
                  不適切な商品の通報
          -if user_signed_in? && current_user.id == @item.user_id
            .my_page_btn
              = link_to "商品の編集", edit_item_path(@item.id), class:"edit_btn"

              = link_to "商品の削除", item_path, method: :delete, class: "destroy_btn"        

          -elsif @item.buyer_id.present?
            .purchase
              = link_to "残念！売切れました", root_path, class: "disabled-button"                
          -else
            .purchase
              = link_to "商品の購入", purchase_path, class:"purchase_btn","data-turbolinks": false             
        .commentBox
          %ul.commentContents
          = form_with url:"#", local: true, class: "new_comment" do |f|
            = f.text_area :comment,class: "textarea"
            %p.noticeMsg
              相手のことを考え丁寧なコメントを心がけましょう
              %br/
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
            = f.submit 'コメントする',class: 'commentBtn' do
              %i.fa.fa-comment
              コメントする
      %ul.links
        %li.right
          = link_to "#" do
            %i.fa.fa-angle-left
            %span
              前の商品
        %li.left
          = link_to "#" do
            %span 
              後ろの商品
            %i.fa.fa-angle-right
      .relatedItems
        =link_to "#" do
          ベビー・キッズをもっと見る
      .productLists
        .productList
          = link_to "/products/8", class: 'link' do
            %figure.productList--img
              = image_tag 'a007.png', alt: 'sakana', class: 'img'
              .productList--body
                %h3.name product3
                .details
                  %ul
                    %li 3000円
                    %li
                      %i.fa.fa-star.lekeIcon 0
                  %p 税込

= render "toppages/footer"
= render "toppages/purchaseBtn"

app/views/items/update.html.haml
.contents_row
  .success
    %h3 更新が完了しました
    = link_to "#",class:"btn" do
      投稿一覧へ戻る
      