config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
  end

  root 'toppages#index'

  resources :mypages do
    collection do
      get 'logout'
      get 'payment'
    end
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase do
    member do
      post 'pay', to: 'purchase#pay'
      get 'index', to: 'purchase#index'
      get 'done', to: 'purchase#done'      
    end
  end

  # resources :login, only: [:index, :new]
  resources :toppages, only: :index
  resources :login, only: :new
  
  resources :items do 
    #Ajaxで動くアクションのルートを作成
    collection do
      get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
      get 'delete',to: 'items#delete'
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  validates :customer_id, presence: true
  validates :card_id, presence: true

end

app/controllers/card_controller.rb
class CardController < ApplicationController

  require "payjp"

  def new
    if user_signed_in?
      card = Card.where(user_id: current_user.id)
      redirect_to action: "show" if card.exists?
    else
      redirect_to new_login_path
      flash[:notice] = '購入するにはログイン・新規登録してください'
    end
  end

  def pay
    Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) 
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  def show
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/new.html.haml
= render "toppages/header"
.payment-wrapper
  = render 'mypages/side_bar'
  .contents-head
    .contents-title
      %h2 クレジットカード情報入力
    .contents__credit-card-wrapper
      .contents__credit-card
        .contents__credit-card__number
          //カード番号入力フォーム
          = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
            %label カード番号
            %span.required 必須
            = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
            %br
            //ブランドロゴ
            %ul.card-list
              %li 
                = image_tag "/material/icon/visa.svg", size: "49x20"
              %li
                = image_tag "/material/icon/master-card.svg", size: "34x20"
              %li
                = image_tag "/material/icon/saison-card.svg", size: "30x20"
              %li
                = image_tag "/material/icon/jcb.svg", size: "32x20"
              %li
                = image_tag "/material/icon/american_express.svg", size: "21x20"
              %li
                = image_tag "/material/icon/dinersclub.svg", size: "32x20"
              %li
            .contents__credit-card__expiration
            //カード有効期限入力フォーム
            %label 有効期限
            %span.required 必須
            %br
              .contents__credit-card__expiration__wrap
                %select#exp_month{name: "exp_month", type: "text", class: 'input-expiration'}
                  %option{value: ""} --
                  %option{value: "1"}01
                  %option{value: "2"}02
                  %option{value: "3"}03
                  %option{value: "4"}04
                  %option{value: "5"}05
                  %option{value: "6"}06
                  %option{value: "7"}07
                  %option{value: "8"}08
                  %option{value: "9"}09
                  %option{value: "10"}10
                  %option{value: "11"}11
                  %option{value: "12"}12
                %span 月
                %select#exp_year{name: "exp_year", type: "text", class: 'input-expiration'}
                  %option{value: ""} --
                  %option{value: "2019"}19
                  %option{value: "2020"}20
                  %option{value: "2021"}21
                  %option{value: "2022"}22
                  %option{value: "2023"}23
                  %option{value: "2024"}24
                  %option{value: "2025"}25
                  %option{value: "2026"}26
                  %option{value: "2027"}27
                  %option{value: "2028"}28
                  %option{value: "2029"}29
                %span 年
                %br
            .contents__credit-card__security-code
              %label セキュリティコード
              %span.required 必須
              %br
              = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
              #card_token
            .content-bottom
              = submit_tag "追加する", id: "token_submit",class: "add-btn"

app/views/card/show.html.haml
= render "toppages/header"
.payment-wrapper
  = render 'mypages/side_bar'
  .payment-info-head
    .payment-info-title
      %h2 登録クレジットカード情報
    .payment-info-wrapper
      .payment-info-wrapper-child
        .payment-info-wrapper-child__cardnumber
          = "カード番号：""**** **** **** " + @default_card_information.last4

        %p.payment-info-wrapper-child__carddate
          - exp_month = @default_card_information.exp_month.to_s
          - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
          = "カード有効期限：" + "20" + exp_year + "年" + exp_month + "月"

        = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
          %input{ type: "hidden", name: "card_id", value: "" }
          %button カード情報を削除する
= render 'toppages/footer'